### ISSUE TITLE
Prepare marketing team structure for 2025

### ISSUE THREAD

**Issue by RyanAbella** [mysteriumnetwork/nightly#6]
Goal: Evaluate and plan team growth.
Task: Identify what kind of resources we will require and how many such people are needed taking into consideration where the key struggles are.
Note: Prepare for a few scenarios. 1. January - June. 2. July - December. 3. Full 2025.
Deadline: 6th December, 2024

**Comment by RyanAbella** [comment]
@GuodaMysterium, how is it going with this? Is there anything to share?

**Comment by GuodaMysterium** [comment]
Hello. Link - https://docs.google.com/spreadsheets/d/1gZpp-81Yf9iWlmDb7uJlvIMkekq7B1yMo9yWWJqSf08/edit?usp=sharing
