### ISSUE TITLE
Referral system survey launch

### ISSUE THREAD

**Issue by RyanAbella** [mysteriumnetwork/nightly#7]
Message on socials discussed: 

We’ve got some exciting plans for the next few quarters, and we could really use your input! :tada:

If Mysterium VPN were to offer referral rewards, what kind of rewards would you prefer? We’d love to hear your thoughts!

Please take a moment to fill out your answers using this form. Your feedback will help us make sure we’re offering something everyone will love!

Thanks so much for your help! :raised_hands:

Questions: If Mysterium VPN were to offer referral rewards, what kind of rewards would you prefer? (can be used different open question). 

Deadline 4th December.

**Comment by RyanAbella** [comment]
@GuodaMysterium, how is the progress with this task? Did the survey question was shared with the community?

**Comment by GuodaMysterium** [comment]
Not yet, will do most likely today.
